baseURL = "http://www.sahil.cc"
languageCode = "en-us"
title = "Sahil's Journal"
theme = "hugo-future-imperfect"
enableRobotsTXT = true
pygmentsuseclasses = true #Run https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css by
#hugo gen chromastyles --style=default > static/css/syntax.css
pygmentsCodeFences = true  #https://gohugo.io/content-management/syntax-highlighting/#highlight-in-code-fences
canonifyurls = true
disqusShortname = "sahil-cc"
googleAnalytics = "UA-87967706-1"
publishDir = "docs"

#From future imperfect:
#preserveTaxonomyNames = true
paginate = 6
pluralizeListTitles = false

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please mention source if you want to quote or reproduce."

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

#[permalinks]
#  post = "/:year/:month/:title/"

# Add your own params here
[params]
#  author = "Sahil Ahuja"
#  avatar = "/img/avatar.png"
#  seotitle = "Sahil's Journal"
#  subtitle = "~ Keep It Simple & Stupid ~"
#  paginate = 10
  # Sets the navbarTitle that appears in the top left of the navigation bar
  navbarTitle = "sahil.cc"
  # Sets the meta tag description
  description = "One day at a time. One problem at a time."
  # Sets where "View More Posts" links
  viewMorePostLink     = "/post/"

# Optional Params
  # Sets navbarTitle to match the section of the website
  dynamicTitles        = true
  # Sets RSS icons to appear on the sidebar with the social media buttons
  rssAppearAtTop       = true
  rssAppearAtBottom    = true
  # Sets Social Media icons to appear on the sidebar
  socialAppearAtTop    = true
  socialAppearAtBottom = true
  # Sets Categories to sort by number of posts instead of alphabetical
  categoriesByCount    = true
  # Sets Estimated Reading Time to appear in post headers
  includeReadingTime   = true
  # Sets the Favicon and Version for the site. Default support is for
  # apple-touch-icon-precomposed.png, favicon.png, favicon.ico, and mstile.png.
  # These are stored in the favicon folder. See the following for more information:
  # https://github.com/audreyr/favicon-cheat-sheet
  loadFavicon          = false
  faviconVersion       = ""
  # Sets Social Share links to appear on posts
  socialShare          = true
  # Load custom CSS or JavaScript files. The variable is an array so that you
  # can load multiple files if necessary. You can also load the standard theme
  # files by adding the value, "default".
  customCSS            = ["default", "/css/syntax.css", "/css/bugfix.css"]
  # customJS             = ["default", "/path/to/file"]
  customJS             = ["default"]


# These are optional params related to the sidebar. They are recommended, but not
# required for proper functionality. HTML is supported within the params.
[params.intro]
  header    = "Sahil Ahuja"
  paragraph = "~ Keep It Simple & Stupid ~ <i class='fa fa-hand-peace-o'></i>"
  about     = "The programmer, like the poet, works only slightly removed from pure thought-stuff. He builds his castles in the air, from air, creating by exertion of the imagination."

  # This appears at the top of the sidebar above params.intro.header.
  # A width of less than 100px is recommended from a design perspective.
  [params.intro.pic]
    src       = "/img/avatar.png"
    # Sets Image to be a cirlce
    circle    = false
    # Sets Image to be Future Imperfect's hexagon
    imperfect = false
    width     = "105"
    alt       = "Coder Dojo"

[params.postAmount]
# Sets the number of recent posts to show in the sidebar. The default value is 5.
    sidebar = 4

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  identifier = "fa fa-id-card-o"
  weight = 2

[[menu.main]]
  name = "Quotes"
  url = "/quotes/"
  identifier = "fa fa-list"
  weight = 3

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  identifier = "fa fa-sitemap"
  weight = 4

[[menu.main]]
  name = "GMETRI"
  url = "https://gmetri.com/"
  identifier = "fa fa-newspaper-o"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  identifier = "fa fa-envelope-o"
  weight = 6

[social]
  # Choose your social networks
  email = "sahilahuja@gmail.com"
  github = "sahil87"
  twitter = "_sahilahuja"
  linkedin = "ahujasahil"
  #weibo = "weibo_username"
  #wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  facebook = "ahujasahil"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  medium = "sahilahuja"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"

  # Google Webmaster
  # https://www.google.com/webmasters/
  # googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"

  # Bing Webmaster
  # https://www.bing.com/toolbox/webmaster/
  # msValidate = "22596E34341DD1D17D6022C44647E587"

  # Baidu Webmaster (China Only)
  # https://zhanzhang.baidu.com/
  # baiduSiteVerification = "MZ23SPxxfa"

  # Sogou Webmaster (China Only)
  # http://zhanzhang.sogou.com/
  # sogouSiteVerification = "m2jktMQTZm"

  # 360 Webmaster (China Only)
  # http://zhanzhang.so.com/
  # soSiteVerification = "b7ab3b4c2edbc856642004d1b8c27a91"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  # baiduTongji = "e21dc1e8a592188271b615159dc88af7"

  # ICP Number (China Only)
  # ICP = "苏ICP备16005986号-2"